version: '3.8'

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: promenade-caddy
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/caddy:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - traefik-proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.promenade.rule=Host(`promenade.example.com`)" # Change to your domain
      - "traefik.http.routers.promenade.entrypoints=websecure"
      - "traefik.http.routers.promenade.tls=true"
      - "traefik.http.routers.promenade.tls.certresolver=letsencrypt"
      - "traefik.http.services.promenade.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-proxy"
      # Health check
      - "traefik.http.services.promenade.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.promenade.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.promenade.loadbalancer.healthcheck.timeout=5s"
      # Optional middlewares for security
      - "traefik.http.routers.promenade.middlewares=secure-headers@file"

volumes:
  caddy_data:
  caddy_config:

networks:
  internal:
    name: promenade-internal
  traefik-proxy:
    external: true
    name: traefik-proxy 